# -*- coding: utf-8 -*-
"""cs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VMcnvV5L1x5doivpDflI8CS2xc0BcJFY
"""

import re
import sys
from sklearn.metrics import confusion_matrix
import time
import datetime

import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn import metrics
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from google.colab import files

# Loading the data
uploaded = files.upload()

df = pd.read_csv('hygdata_v3.csv')

df.head()